# Generated by Django 3.2 on 2023-01-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wished_product',
            new_name='product',
        ),
    ]
