# Generated by Django 3.2 on 2022-11-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221124_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
