# Generated by Django 3.2 on 2022-11-27 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pegi',
            field=models.CharField(blank=True, default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
